// One lint configuration for the whole repository, at the root, because the
// two halves of this app are one codebase and disagreeing about rules across
// backend/ and frontend/ would be an argument nobody benefits from.
//
// Recommended rules only. No stylistic rules live here — Prettier owns layout,
// and eslint-config-prettier is applied last to switch off anything ESLint
// might otherwise say about it. A lint error in this repo should always mean
// "this code is wrong", never "this code is formatted differently".

import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import prettier from "eslint-config-prettier";

export default [
  {
    ignores: [
      "**/node_modules/**",
      "frontend/dist/**",
      // Built frontend, copied in by the Dockerfile. Vite's output, not ours.
      "backend/public/**",
      // Generated by scripts/build-content.mjs. Editing them here to please a
      // linter would put them out of step with content/questions.source.json,
      // which is the one file that decides the deck.
      "frontend/src/content/questions.json",
      "backend/deck.json",
      // Terraform. ESLint has nothing to say about HCL.
      "infra/**",
      // Browser-automation scratch output.
      ".playwright-mcp/**",
      // Task checkouts, one per branch. Each is linted from its own root.
      "worktrees/**",
    ],
  },

  js.configs.recommended,

  // Everything that runs in Node: the zero-dependency HTTP server, its
  // node --test suites, and the content pipeline.
  {
    files: ["backend/**/*.js", "scripts/**/*.{js,mjs}", "*.js", "frontend/vite.config.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: globals.node,
    },
  },

  // Everything that runs in a browser. React 18 with the automatic JSX
  // runtime, so React is not required to be in scope and no react-in-jsx-scope
  // rule is wanted here.
  {
    files: ["frontend/src/**/*.{js,jsx}"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: globals.browser,
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    plugins: { "react-hooks": reactHooks },
    // Two rules, named rather than taken from the plugin's `recommended`.
    // Version 7 promoted the React Compiler's own analyses into that preset,
    // so the name that used to mean these two now means sixteen — and the new
    // ones disagree with deliberate code here, such as reading a ref during
    // render to report the clock offset. These two are the ones this repo
    // wants enforced: hooks called unconditionally, and dependency arrays that
    // are at least questioned.
    rules: {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
    },
  },

  // Last, and it must stay last: this turns rules off, so anything after it
  // could turn them back on.
  prettier,
];
