#!/usr/bin/env node
// Split the single authored content file into the two files the app consumes.
//
//   content/questions.source.json          <- the ONLY file a human edits
//     |-> frontend/src/content/questions.json   what the room reads: the text,
//     |                                         the media, the words on the buttons
//     |-> backend/deck.json                     what the server runs: which
//                                               questions exist, and for how long
//
// This exists because the two outputs used to be hand-maintained and aligned
// only by convention. The server decides which questions exist and how long
// each one stays open; the bundle decides what the room reads while it does.
// Nothing checked that the two lists named the same questions, and a deck id
// the bundle has never heard of is a blank panel on the projector — while a
// countdown that differs between them is a bar drawn against a length the
// server is not enforcing.
//
// WIRE FORMAT. The server only ever knows about opaque choice keys — "a"
// through "f" — and that is what the state machine, the tally and the dedup are
// built on. This file is where a question's keys get their words.
//
// A question is a scenario and a ballot, and the ballot can be written either
// way:
//
//   (no `options`)          the default pair. Two options, ♥ 可以 and
//                           ✕ 不可以, keyed "a" and "b".
//   options                 any 2-6 options of your own. `options` is a list of
//                           {label, icon} — optionally with image, audio or
//                           video — in the order they appear on the phone,
//                           keyed "a", "b", "c"… by position.
//
// There is no correct answer, and nothing here can mark one. A question that
// still carries `isAi` or `answer` is refused rather than ignored: those belong
// to the quiz this was cloned from, and a deck pasted across from it would
// otherwise build without complaint and leave its author believing an answer
// was still being kept somewhere.
//
// The same option list is also editable per question from the setup page during
// the event; this file is only the default it starts from.
//
//   npm run content          regenerate
//   npm run content:check    fail if the generated files are stale

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("../", import.meta.url));
const SOURCE = `${ROOT}content/questions.source.json`;
const PUBLIC_OUT = `${ROOT}frontend/src/content/questions.json`;
const DECK_OUT = `${ROOT}backend/deck.json`;

const BANNER =
  "GENERATED by scripts/build-content.mjs — edit content/questions.source.json instead";

// Kept in step with OPTION_KEYS in backend/game.js. This script deliberately
// imports nothing from the app: it has to run before either half is installed.
export const OPTION_KEYS = ["a", "b", "c", "d", "e", "f"];
export const MIN_OPTIONS = 2;

// Fields of the quiz this was cloned from. See the header for why they are an
// error here and not merely unused.
const QUIZ_ONLY_FIELDS = ["isAi", "answer"];

// What a question offers when it does not say. A heart and a cross, as plain
// text glyphs — U+2665 and U+2715 — and not as emoji: the app ships its own
// font for exactly these two code points, so they look the same on every
// handset. A heart and a cross rather than a tick and a cross, because that
// pair is how answers get marked, and on a poll with no right answer it would
// tell the room which side is correct before anybody has voted.
// Kept in step with DEFAULT_OPTIONS in frontend/src/lib/choices.js.
export const DEFAULT_OPTIONS = [
  { key: OPTION_KEYS[0], icon: "♥", label: "可以" },
  { key: OPTION_KEYS[1], icon: "✕", label: "不可以" },
];

/** The option list a question offers, keyed by position. */
export function optionsOf(question) {
  if (!Array.isArray(question.options)) return DEFAULT_OPTIONS;
  return question.options.map((option, i) => ({
    key: OPTION_KEYS[i],
    icon: option.icon ?? "",
    label: option.label,
    // Absent media is omitted rather than written as "", matching what the
    // server stores when the setup page saves an option — so a question
    // authored here and a question edited during the show are the same shape.
    ...(option.image ? { image: option.image } : {}),
    ...(option.audio ? { audio: option.audio } : {}),
    ...(option.video ? { video: option.video } : {}),
  }));
}

export function validate(questions) {
  if (!Array.isArray(questions) || questions.length === 0) {
    throw new Error("source must be a non-empty array");
  }

  const seen = new Set();
  for (const [i, q] of questions.entries()) {
    const at = `question ${i + 1} (${q.id ?? "no id"})`;
    if (typeof q.id !== "string" || !q.id) throw new Error(`${at}: missing id`);
    if (seen.has(q.id)) throw new Error(`${at}: duplicate id "${q.id}"`);
    seen.add(q.id);

    for (const field of QUIZ_ONLY_FIELDS) {
      if (field in q) {
        throw new Error(
          `${at}: "${field}" is not used here — this is an opinion poll with no correct answer, so remove it`,
        );
      }
    }

    if (Array.isArray(q.options)) {
      if (q.options.length < MIN_OPTIONS || q.options.length > OPTION_KEYS.length) {
        throw new Error(
          `${at}: options must have between ${MIN_OPTIONS} and ${OPTION_KEYS.length} entries`,
        );
      }
      for (const [j, option] of q.options.entries()) {
        if (!option || typeof option.label !== "string" || !option.label.trim()) {
          throw new Error(`${at}: option ${j + 1} needs a label`);
        }
        for (const kind of ["image", "audio", "video"]) {
          if (option[kind] !== undefined && (typeof option[kind] !== "string" || !option[kind])) {
            throw new Error(`${at}: option ${j + 1} ${kind} must be a non-empty url`);
          }
        }
      }
    }
    if (!Number.isFinite(q.duration) || q.duration <= 0) {
      throw new Error(`${at}: duration must be a positive number of seconds`);
    }
    if (!q.body && !q.image && !q.audio) {
      throw new Error(`${at}: needs a body, an image or an audio clip`);
    }
  }
}

export function build(questions) {
  return {
    // Bundled into the JS that every phone downloads. That used to be a reason
    // to keep things out of it; a poll has no answer for the bundle to give
    // away, so everything a question says is here.
    publicQuestions: questions.map((q) => ({
      _generated: BANNER,
      id: q.id,
      title: q.title,
      topic: q.topic,
      duration: q.duration, // the projector's countdown bar reads this
      body: q.body ?? "",
      image: q.image ?? "",
      audio: q.audio ?? "",
      // The words on the buttons. The phones need the labels to draw anything
      // at all.
      options: optionsOf(q),
      note: q.note,
    })),
    // What the server needs in order to run the show and nothing else: which
    // questions exist, in what order, and how long each one stays open.
    deck: questions.map((q) => ({
      _generated: BANNER,
      id: q.id,
      duration: q.duration,
    })),
  };
}

function readOrNull(path) {
  try {
    return readFileSync(path, "utf8");
  } catch {
    return null;
  }
}

function main() {
  const check = process.argv.includes("--check");
  const questions = JSON.parse(readFileSync(SOURCE, "utf8"));
  validate(questions);

  const { publicQuestions, deck } = build(questions);
  let drifted = false;

  for (const [path, data] of [
    [PUBLIC_OUT, publicQuestions],
    [DECK_OUT, deck],
  ]) {
    const next = `${JSON.stringify(data, null, 2)}\n`;
    if (readOrNull(path) === next) continue;

    drifted = true;
    if (check) {
      console.error(`stale: ${path.replace(ROOT, "")}`);
    } else {
      writeFileSync(path, next);
      console.log(`wrote ${path.replace(ROOT, "")}`);
    }
  }

  if (check && drifted) {
    console.error("\nRun `npm run content` and commit the result.");
    process.exit(1);
  }
  if (!check && !drifted) console.log("already up to date");

  console.log(
    `${questions.length} questions · durations ${questions.map((q) => q.duration).join(" ")}`,
  );
}

main();
